# -*- coding: utf-8 -*-
"""Sistema de Gráficos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ldJVq9p5o3C5FnwR0FC2uYvC3yWJkxK0
"""

import matplotlib.pyplot as plt
#Tendência de Estoque Diário

dias = [1, 2, 3, 4, 5, 6, 7]
estoque = [100, 95, 110, 105, 120, 115, 130]

plt.plot(dias, estoque, color="darkblue")
plt.title('Tendência de Estoque Diário')
plt.xlabel('Dias')
plt.ylabel('Quantidade em Estoque')
plt.grid(True, linestyle='--', alpha=0.7, color="black")
plt.xticks(dias)
ax = plt.gca()
ax.set_facecolor('lightblue')
plt.legend("Gráfico ilustrativo para a tendência de estoque diário, crescimentos e quedas.")
plt.show()

import matplotlib.pyplot as plt
# Comparação de Produtos

produtos = ["Teclado", "Mouse", "Monitor", "Webcam"]
quantidade = [50, 75, 30, 60]

plt.bar(produtos, quantidade, color="purple")
ax = plt.gca()
ax.set_facecolor('lightyellow')
plt.title("Comparação de produtos")
plt.xlabel('Produtos')
plt.ylabel('Quantidade')
plt.legend("Gráfico ilustrativo para a diferença no número de vendas entre os principais produtos.")
plt.show()

import matplotlib.pyplot as plt
# Proporção de Categorias

categoria = ['Eletrónicos', "Vestuários", "Alimentos"]
valores = [15000, 8000, 5000]

plt.title("Gastos Mensais")
plt.pie(valores, labels=categoria, autopct='%1.1f%%', startangle=90, colors=['pink', 'purple', 'lightyellow'])
ax = plt.gca()
plt.show()

import matplotlib.pyplot as plt
# Preço vs. Quantidade

precos = [50, 120, 300, 80, 20]
estoque = [80, 25, 10, 70, 150]

plt.figure(figsize=(10, 6))
plt.scatter(precos, estoque, color="red")
plt.title('Relação entre preço e quantidade em estoque')
plt.xlabel('Preços')
plt.ylabel('Estoque')
plt.xticks(precos)
plt.grid(True, linestyle='--', alpha=1)
plt.tight_layout()
plt.show()